#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##################### Configuration of 'orderdb' by group sharding v5.1.0 #######################

# External logical database schema.
schemaName: orderdb

# Extension default datasource configuration.
# @see:com.wl4g.shardingproxy.config.ProxyConfigurationLoader2.loadRuleConfiguration
extensionDefaultDataSource:
  username: root
  password: 123456
  connectionTimeoutMilliseconds: 30000
  idleTimeoutMilliseconds: 60000
  maxLifetimeMilliseconds: 1800000
  maxPoolSize: 50
  minPoolSize: 1

# Specification datasource configuration.
dataSources:
  ## MGR cluster 0
  ## Instance 0
  ds_orderdb_db0:
    url: 'jdbc:mysql://n0.rds.local:3306/orderdb_db0?serverTimezone=UTC&useSSL=false&allowMultiQueries=true&characterEncoding=utf-8'
  ds_orderdb_db1:
    url: 'jdbc:mysql://n0.rds.local:3306/orderdb_db0?serverTimezone=UTC&useSSL=false&allowMultiQueries=true&characterEncoding=utf-8'
  ## Instance 1
  ds_orderdb_db0_r1:
    url: 'jdbc:mysql://n1.rds.local:3306/orderdb_db0?serverTimezone=UTC&useSSL=false&allowMultiQueries=true&characterEncoding=utf-8'
  ds_orderdb_db1_r1:
    url: 'jdbc:mysql://n1.rds.local:3306/orderdb_db1?serverTimezone=UTC&useSSL=false&allowMultiQueries=true&characterEncoding=utf-8'
  ## Instance 2
  ds_orderdb_db0_r2:
    url: 'jdbc:mysql://n2.rds.local:3306/orderdb_db0?serverTimezone=UTC&useSSL=false&allowMultiQueries=true&characterEncoding=utf-8'
  ds_orderdb_db1_r2:
    url: 'jdbc:mysql://n2.rds.local:3306/orderdb_db1?serverTimezone=UTC&useSSL=false&allowMultiQueries=true&characterEncoding=utf-8'
  ## MGR cluster 1
  ## Instance 0
  ds_orderdb_db2:
    url: 'jdbc:mysql://n0.rds.local:3306/orderdb_db2?serverTimezone=UTC&useSSL=false&allowMultiQueries=true&characterEncoding=utf-8'
  ds_orderdb_db3:
    url: 'jdbc:mysql://n0.rds.local:3306/orderdb_db3?serverTimezone=UTC&useSSL=false&allowMultiQueries=true&characterEncoding=utf-8'
  ## Instance 1
  ds_orderdb_db2_r1:
    url: 'jdbc:mysql://n1.rds.local:3306/orderdb_db2?serverTimezone=UTC&useSSL=false&allowMultiQueries=true&characterEncoding=utf-8'
  ds_orderdb_db3_r1:
    url: 'jdbc:mysql://n1.rds.local:3306/orderdb_db3?serverTimezone=UTC&useSSL=false&allowMultiQueries=true&characterEncoding=utf-8'
  ## Instance 2
  ds_orderdb_db2_r2:
    url: 'jdbc:mysql://n2.rds.local:3306/orderdb_db2?serverTimezone=UTC&useSSL=false&allowMultiQueries=true&characterEncoding=utf-8'
  ds_orderdb_db3_r2:
    url: 'jdbc:mysql://n2.rds.local:3306/orderdb_db3?serverTimezone=UTC&useSSL=false&allowMultiQueries=true&characterEncoding=utf-8'
  ## MGR cluster single (no-sharding)
  ds_orderdb_single:
    url: 'jdbc:mysql://n0.rds.local:3306/orderdb_single?serverTimezone=UTC&useSSL=false&allowMultiQueries=true&characterEncoding=utf-8'

# Schema rules configuration.
rules:
## @see:org.apache.shardingsphere.singletable.config.SingleTableRuleConfiguration
## @see:org.apache.shardingsphere.singletable.yaml.config.swapper.SingleTableRuleConfigurationYamlSwapper#getRuleTagName
- !SINGLE
  defaultDataSource: ds_orderdb_single
## @see:https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/builtin-algorithm/sharding/
## @see:org.apache.shardingsphere.sharding.api.config.ShardingRuleConfiguration
## @see:org.apache.shardingsphere.sharding.route.engine.type.standard.ShardingStandardRoutingEngine#route
- !SHARDING
  tables:
    t_order:
      # Union collection definition of all available actual dataSources.
      actualDataNodes: rw_orderdb_db${0..3}.t_order_${0..3}
      #databaseStrategy:
      tableStrategy:
        standard:
          shardingColumn: id
          shardingAlgorithmName: alg_table_boundary_range_g0_0
      keyGenerateStrategy:
        column: id
        keyGeneratorName: gen_snowflake_g0_0
  bindingTables:
  - t_order
  defaultTableStrategy:
  defaultDatabaseStrategy:
    standard:
      shardingColumn: id
      shardingAlgorithmName: alg_database_inline_g0_0
  keyGenerators:
    gen_snowflake_g0_0:
      type: SNOWFLAKE
      props:
        worker-id: '1' # Range[0,1024),see:org.apache.shardingsphere.sharding.algorithm.keygen.SnowflakeKeyGenerateAlgorithm#getWorkerId()
  shardingAlgorithms:
    ## @see:org.apache.shardingsphere.sharding.algorithm.sharding.inline.InlineShardingAlgorithm
    alg_database_inline_g0_0:
      type: INLINE
      props:
        algorithm-expression: rw_orderdb_db${(id % 4) as int}
        allow-range-query-with-inline-sharding: true
    ## @see:org.apache.shardingsphere.sharding.algorithm.sharding.range.VolumeBasedRangeShardingAlgorithm
    alg_table_volume_range_g0_0:
      type: VOLUME_RANGE
      props: # Must use quotation marks(string) or you cannot get them.
        range-lower: '0'
        range-upper: '80000000' # dbCount*tableCount*500w=4*4*500w=8000w
        ## Tips: In the production environment, it is recommended that the data volume of a single table should be less than 500w based on internet application.
        sharding-volume: '20000000'
    ## @see:org.apache.shardingsphere.sharding.algorithm.sharding.range.VolumeBasedRangeShardingAlgorithm
    alg_table_boundary_range_g0_0:
      type: BOUNDARY_RANGE
      props: # dbCount*tableCount*500w=4*4*500w=8000w
        sharding-ranges: "20000000,40000000,60000000,80000000"
## @see:org.apache.shardingsphere.readwritesplitting.api.ReadwriteSplittingRuleConfiguration
- !READWRITE_SPLITTING
  dataSources:
    rw_orderdb_db0:
      writeDataSourceName: ds_orderdb_db0
      readDataSourceNames:
        - ds_orderdb_db0_r1
        - ds_orderdb_db0_r2
      loadBalancerName: r_lb_0
    rw_orderdb_db1:
      writeDataSourceName: ds_orderdb_db1
      readDataSourceNames:
        - ds_orderdb_db1_r1
        - ds_orderdb_db1_r2
      loadBalancerName: r_lb_0
    rw_orderdb_db2:
      writeDataSourceName: ds_orderdb_db2
      readDataSourceNames:
        - ds_orderdb_db2_r1
        - ds_orderdb_db2_r2
    rw_orderdb_db3:
      writeDataSourceName: ds_orderdb_db3
      readDataSourceNames:
        - ds_orderdb_db3_r1
        - ds_orderdb_db3_r2
      loadBalancerName: r_lb_0
  loadBalancers:
    r_lb_0:
      type: RANDOM
## @see:org.apache.shardingsphere.readwritesplitting.api.DatabaseDiscoveryRuleConfiguration
- !DB_DISCOVERY
   dataSources:
     ha_orderdb_:
       discoveryTypeName: default_dis_mgr
       discoveryHeartbeatName: default_mgr_heartbeat
       dataSourceNames:
         # Instance 0
         - ds_orderdb_db0
         - ds_orderdb_db1
         # Instance 1
         - ds_orderdb_db0_r1
         - ds_orderdb_db1_r1
         # Instance 2
         - ds_orderdb_db0_r2
         - ds_orderdb_db1_r2
     ha_orderdb_:
       discoveryTypeName: default_dis_mgr
       discoveryHeartbeatName: default_mgr_heartbeat
       dataSourceNames:
         # Instance 0
         - ds_orderdb_db0
         - ds_orderdb_db1
         # Instance 1
         - ds_orderdb_db0_r1
         - ds_orderdb_db1_r1
         # Instance 2
         - ds_orderdb_db0_r2
         - ds_orderdb_db1_r2
   discoveryHeartbeats:
     default_mgr_heartbeat:
       props:
         keep-alive-cron: '0/5 * * * * ?'
   discoveryTypes:
     # HA MGR architecture see: https://blog.csdn.net/n88Lpo/article/details/118315051
     default_dis_mgr:
       type: MGR
       props:
         # Must be consistent with the MGR configuration group name.
         # see: https://github.com/apache/shardingsphere/blob/5.1.0/shardingsphere-features/shardingsphere-db-discovery/shardingsphere-db-discovery-provider/shardingsphere-db-discovery-mgr/src/main/java/org/apache/shardingsphere/dbdiscovery/mgr/MGRDatabaseDiscoveryType.java#L104
         # see: https://github.com/mysql/mysql-server/blob/mysql-5.7.30/rapid/plugin/group_replication/src/plugin.cc#L1726
         # see: SELECT * FROM performance_schema.global_variables WHERE VARIABLE_NAME='group_replication_group_name'
         group-name: 5db40c3c-180c-11e9-afbf-005056ac6820
         ## @see:org.apache.shardingsphere.dbdiscovery.mgr.MGRDatabaseDiscoveryType#extDiscoveryConfig
         extensionDiscoveryConfigJson: |-
           {
             "memberHostMappings": [{
                 "rds-mgr-0:3306": [
                     "n0.rds.local:3306"
                 ]
             }, {
                 "rds-mgr-1:3306": [
                     "n1.rds.local:3306"
                 ]
             }, {
                 "rds-mgr-2:3306": [
                     "n2.rds.local:3306"
                 ]
             }]
           }
