apiVersion: v1
kind: Service
metadata:
  name: {{ include "shardingproxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "shardingproxy.name" . }}
    helm.sh/chart: {{ include "shardingproxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- if .Values.service.externalIPs }}
  externalIPs: {{- toYaml .Values.service.externalIPs | nindent 4 }}
  {{- end }}
  {{- end }}
  ports:
  - name: proxy
    port: {{ .Values.service.proxy | default 3308 }}
    protocol: TCP
    targetPort: proxy
    {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePorts.proxy)) }}
    nodePort: {{ .Values.service.nodePorts.proxy }}
    {{- else if eq .Values.service.type "ClusterIP" }}
    nodePort: null
    {{- end }}

  - name: dashboard
    port: {{ .Values.service.dashboard | default 18083 }}
    protocol: TCP
    targetPort: dashboard
    {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePorts.dashboard)) }}
    nodePort: {{ .Values.service.nodePorts.dashboard }}
    {{- else if eq .Values.service.type "ClusterIP" }}
    nodePort: null
    {{- end }}

  {{- if not (empty .Values.service.prometheus) }}
  - name: prometheus
    port: {{ .Values.service.prometheus | default 10108 }}
    protocol: TCP
    targetPort: prometheus
    {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePorts.prometheus)) }}
    nodePort: {{ .Values.service.nodePorts.prometheus }}
    {{- else if eq .Values.service.type "ClusterIP" }}
    nodePort: null
    {{- end }}

  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "shardingproxy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "shardingproxy.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "shardingproxy.name" . }}
    helm.sh/chart: {{ include "shardingproxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  sessionAffinity: None
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: proxy
    port: {{ .Values.service.proxy | default 3308 }}
    protocol: TCP
    targetPort: proxy

  - name: dashboard
    port: {{ .Values.service.dashboard | default 18083 }}
    protocol: TCP
    targetPort: dashboard

  - name: prometheus
    port: {{ .Values.service.prometheus | default 10108 }}
    protocol: TCP
    targetPort: prometheus

  selector:
    app.kubernetes.io/name: {{ include "shardingproxy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
